In [299]:
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from matplotlib import cm
%matplotlib qt

In [300]:
# Probability Parameters

D = 0.6 # Probability that A[i,j] starts as vegetation and not an empty cell
B = 0.25 # Probability that a burning cell becomes burnt
I = 0.2 # Probability that a burning cell turns its vegetation into burning


In [301]:
def display(A):
    maxX = A.shape[0]
    maxY = A.shape[1]
    B = np.zeros((maxY, maxX))
    for ix in range(0,maxX):
        for iy in range(0,maxY):
            B[maxY-1-iy,ix] = A[ix,iy]

    #Display the graphics outside of the notebook. 
    #On a PC, use '%matplotlib qt' instead.
    %matplotlib qt 
    
    fig.clear()
    plt.rcParams['figure.figsize'] = [10, 10/maxX*maxY]
    plt.imshow(B, cmap='Dark2'); 
    plt.axis('off'); 
    plt.show()
    plt.draw()
    plt.pause(0.01)
    writer.grab_frame()
    

In [302]:
# Initialize matrix containing all 2D grid points A(x,y)
A = np.zeros((maxX, maxY))

# Fill points in as vegetation depending on D
# 0 = tree (green), 1 = burning (orange), 4 = empty (brown), 5 = burnt (gray) 
# to match color map
for i in range(maxX):
    for j in range(maxY):
        p = np.random.random()
        if p < D:
            A[i,j] = 0
        elif p > .999:
            A[i,j] = 1
        else:
            A[i,j] = 4
            
# start some burning in center of grid if not empty
# for i in range(maxX):
#     for j in range(maxY):
#         if (i-250)**2 + (j-250)**2 < 100:
#             if A[i,j] == 0:
#                 A[i,j] = 1;
            
# Make border all empty cells to simplify boundary conditions            
A[:,0] = 4
A[:,maxY-1] = 4
A[maxX-1,:] = 4
A[0,:] = 4
A[0,0] = 5
        
print(A.transpose())

[[5. 4. 4. ... 4. 4. 4.]
 [4. 0. 0. ... 4. 0. 4.]
 [4. 4. 0. ... 0. 0. 4.]
 ...
 [4. 0. 0. ... 0. 0. 4.]
 [4. 4. 4. ... 0. 0. 4.]
 [4. 4. 4. ... 4. 4. 4.]]


In [303]:
from matplotlib.animation import FFMpegWriter
metadata = dict(title='Forest Fire Simulation', artist='Emily',comment='Final Project')
writer = FFMpegWriter(fps=15, metadata=metadata)
fig = plt.figure()
with writer.saving(fig, "Animation3.mp4", dpi=200):
    n_steps = 500
    for t in range(n_steps):
        A_new = A[:]
        burning = False
        for i in range(maxX):
            for j in range(maxY):
                if A[i,j] == 1: #if cell is burning
                    burning = True
                    #check if cell should become burnt
                    if np.random.random() < I: 
                        A_new[i,j] = 5

                    #check if vegetation neighbors of burning cell should become burning
                    for g in range(i-1,i+2): 
                        for h in range(j-1,j+2):
                            if A[g,h] == 0:
                                if np.random.random() < B:
                                    A_new[g,h] = 1
        A = A_new[:]
        if t % 10 == 0:
            plt.clf()
            plt.rcParams['figure.figsize'] = [10, 10/maxX*maxY]
            plt.imshow(A, cmap='Dark2'); 
            plt.axis('off'); 
            plt.show()
            plt.draw()
            plt.pause(0.01)
            writer.grab_frame()
        if burning == False:
            break
        
                